apiVersion: v1
kind: Service
metadata:
  name: {{ include "openobserve.fullname" . }}-querier
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "openobserve.labels" . | nindent 4 }}
    prometheus.io/scrape: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "openobserve.selectorLabels" . | nindent 4 }}
    role: querier
