apiVersion: v1
kind: Service
metadata:
  name: dex
  namespace: o2e
spec:
  ports:
    - port: 5556
      targetPort: 5556
  selector:
    app: dex

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: o2e
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
    spec:
      containers:
        - name: openldap
          image: osixia/openldap:latest
          # OpenLDAP configuration
          env:
          - name: LDAP_ORGANISATION
            value: "o2"
          - name: LDAP_DOMAIN
            value: "o2.ai"
          - name: LDAP_ADMIN_PASSWORD
            value: "Z54H7w5WQUARsLKaumM967iX62msTEno"  

---
apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: o2e
spec:
  ports:
    - port: 389
      targetPort: 389
  selector:
    app: openldap

