apiVersion: v1
kind: Secret
metadata:
  name: super-secret
type: Opaque
stringData:
  ZO_ROOT_USER_EMAIL: "root@example.com"
  ZO_ROOT_USER_PASSWORD: "Complexpass#123"

  # do not need to set this if enabled minio is being used. settings will be picked from minio section. Also IRSA is preferred if on EKS. Set the Service account section with the correct IAM role ARN. Refer https://zinc.dev/docs/guide/ha_deployment/#amazon-eks-s3
  ZO_S3_ACCESS_KEY: ""
  ZO_S3_SECRET_KEY: ""

  AZURE_STORAGE_ACCOUNT_KEY: ""
  AZURE_STORAGE_ACCOUNT_NAME: ""
  ZO_META_POSTGRES_DSN: "postgres://openobserve:Batman123@o2-openobserve-postgres-rw:5432/app"
  OPENFGA_DATASTORE_URI: "postgres://openobserve:Batman123@o2-openobserve-postgres-rw:5432/app"
  ZO_META_POSTGRES_RO_DSN: ""
  ZO_TRACING_HEADER_KEY: "Authorization"
  ZO_TRACING_HEADER_VALUE: "Basic cm9vdEBleGFtcGxlLmNvbTpDb21wbGV4cGFzcyMxMjM="
  ZO_RUM_CLIENT_TOKEN: ""
  ZO_REPORT_USER_EMAIL: "" # Check details at https://github.com/openobserve/o2_report_server
  ZO_REPORT_USER_PASSWORD: ""
  ZO_SMTP_USER_NAME: "ABAAQQQQFFFFF" # Replace with your own SMTP username
  ZO_SMTP_PASSWORD: "+fjlahsguykevfkajvjk#jsbj43$bjkjbkk" # Replace with your own SMTP password
