apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openobserve.fullname" . }}-alertmanager
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "openobserve.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.alertmanager }}
  selector:
    matchLabels:
      {{- include "openobserve.selectorLabels" . | nindent 6 }}
      role: alertmanager
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openobserve.selectorLabels" . | nindent 8 }}
        role: alertmanager
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openobserve.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: check-etcd
          image: busybox
          command: ['sh', '-c', '
            until nc -z {{ .Release.Name }}-etcd 2379; do
              echo "Waiting for etcd to be ready";
              sleep 5;
            done;
          ']
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5080
              protocol: TCP
          {{- if .Values.probes.alertmanager.enabled }}
          livenessProbe:
           httpGet:
             path: /healthz
             port: http
           initialDelaySeconds: {{ .Values.probes.alertmanager.initialDelaySeconds | default 60 }}
           failureThreshold: {{ .Values.probes.alertmanager.failureThreshold | default 3 }}
          readinessProbe:
           httpGet:
             path: /healthz
             port: http
           initialDelaySeconds: {{ .Values.probes.alertmanager.initialDelaySeconds | default 60 }}
           failureThreshold: {{ .Values.probes.alertmanager.failureThreshold | default 3 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources.alertmanager | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ include "openobserve.fullname" . }}
            - configMapRef:
                name: {{ include "openobserve.fullname" . }}
          env:
            - name: ZO_NODE_ROLE
              value: "alertmanager"
            {{- with .Values.extraEnv }}
            {{- toYaml . |  nindent 12 }}
            {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations.alertmanager }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
