apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openobserve.fullname" . }}-alertquerier
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "openobserve.labels" . | nindent 4 }}
data:
  ZO_CLUSTER_NAME: "{{ .Values.config.ZO_CLUSTER_NAME }}-alertquerier"
