apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openobserve.fullname" . }}-compactor
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "openobserve.labels" . | nindent 4 }}
data:
  ZO_COMPACT_MAX_FILE_SIZE: "{{ .Values.config.ZO_COMPACT_MAX_FILE_SIZE }}"
