{{ if .Values.ingester.headless.enabled}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openobserve.fullname" . }}-ingester-headless
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "openobserve.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.http_port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpc_port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "openobserve.selectorLabels" . | nindent 4 }}
    role: ingester
{{- end }}
