{{- if and .Values.enterprise.enabled .Values.enterprise.o2ai.enabled .Values.enterprise.o2ai.clusterAccess.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openobserve.fullname" . }}-o2ai
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "openobserve.labels" . | nindent 4 }}
  {{- with .Values.enterprise.o2ai.clusterAccess.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
