{{- if .Values.scriptserver.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openobserve.fullname" . }}-scriptserver
  namespace: {{ .Values.scriptserver.namespaces.executor | quote }}
  labels:
    {{- include "openobserve.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.http_port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "openobserve.selectorLabels" . | nindent 4 }}
    role: scriptserver
{{- end }} 