apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openobserve.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "openobserve.labels" . | nindent 4 }}
type: Opaque
stringData:
  ZO_ROOT_USER_EMAIL: "{{ .Values.auth.ZO_ROOT_USER_EMAIL }}"
  ZO_ROOT_USER_PASSWORD: "{{ .Values.auth.ZO_ROOT_USER_PASSWORD }}"
  {{- if not .Values.minio.enabled }}
  ZO_S3_ACCESS_KEY: "{{ .Values.auth.ZO_S3_ACCESS_KEY }}"
  {{- else }}
  ZO_S3_ACCESS_KEY: "{{ .Values.minio.rootUser }}"
  {{- end }}
  {{- if not .Values.minio.enabled }}
  ZO_S3_SECRET_KEY: "{{ .Values.auth.ZO_S3_SECRET_KEY }}"
  {{- else }}
  ZO_S3_SECRET_KEY: "{{ .Values.minio.rootPassword }}"
  {{- end }}
  {{- if eq .Values.config.ZO_S3_PROVIDER "azure" }}
  {{- if .Values.auth.AZURE_STORAGE_ACCOUNT_KEY }}
  AZURE_STORAGE_ACCOUNT_KEY: "{{ .Values.auth.AZURE_STORAGE_ACCOUNT_KEY }}"
  AZURE_STORAGE_ACCOUNT_NAME: "{{ .Values.auth.AZURE_STORAGE_ACCOUNT_NAME }}"  
  {{- else }}
  AZURE_STORAGE_ACCOUNT_KEY: "{{ .Values.config.AZURE_STORAGE_ACCOUNT_KEY }}"
  AZURE_STORAGE_ACCOUNT_NAME: "{{ .Values.config.AZURE_STORAGE_ACCOUNT_NAME }}"  
  {{- end }}
  {{- end }}
  {{- if .Values.postgres.enabled }}
  ZO_META_POSTGRES_DSN: "postgres://openobserve:{{ .Values.postgres.spec.password }}@{{ include "openobserve.fullname" . }}-postgres-rw.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:5432/app?sslmode=disable"
  {{- else }}
  ZO_META_POSTGRES_DSN: "{{ .Values.auth.ZO_META_POSTGRES_DSN }}"
  {{- end }}
  {{- if .Values.auth.ZO_META_MYSQL_DSN }}
  ZO_META_MYSQL_DSN: "{{ .Values.auth.ZO_META_MYSQL_DSN }}"
  {{- else }}
  ZO_META_MYSQL_DSN: "{{ .Values.config.ZO_META_MYSQL_DSN }}"
  {{- end }}
  {{- if .Values.auth.ZO_TRACING_HEADER_KEY }}
  ZO_TRACING_HEADER_KEY: "{{ .Values.auth.ZO_TRACING_HEADER_KEY }}"
  {{- else }}
  ZO_TRACING_HEADER_KEY: "{{ .Values.config.ZO_TRACING_HEADER_KEY }}"
  {{- end }}
  {{- if .Values.auth.ZO_TRACING_HEADER_VALUE }}
  ZO_TRACING_HEADER_VALUE: "{{ .Values.auth.ZO_TRACING_HEADER_VALUE }}"
  {{- else }}
  ZO_TRACING_HEADER_VALUE: "{{ .Values.config.ZO_TRACING_HEADER_VALUE }}"
  {{- end }}
  {{- if .Values.auth.ZO_RUM_CLIENT_TOKEN }}
  ZO_RUM_CLIENT_TOKEN: "{{ .Values.auth.ZO_RUM_CLIENT_TOKEN }}"
  {{- else }}
  ZO_RUM_CLIENT_TOKEN: "{{ .Values.config.ZO_RUM_CLIENT_TOKEN }}"
  {{- end }}