apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "openobserve.fullname" . }}-alertquerier
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "openobserve.labels" . | nindent 4 }}
spec:
  serviceName: "{{ include "openobserve.fullname" . }}-alertquerier"
  replicas: {{ .Values.replicaCount.alertquerier }}
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0  # Set to 0 to allow all pods to update in parallel
  selector:
    matchLabels:
      {{- include "openobserve.selectorLabels" . | nindent 6 }}
      role: alertquerier
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        checksum/specific-config: {{ include (print $.Template.BasePath "/alertquerier-configmap.yaml") . | sha256sum }}
        checksum/generic-config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "openobserve.selectorLabels" . | nindent 8 }}
        role: alertquerier
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openobserve.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- if .Values.etcd.enabled }}
        - name: check-etcd
          image: {{ .Values.image.busybox.repository }}:{{ .Values.image.busybox.tag }}
          command: ['sh', '-c', '
            until nc -z {{ .Release.Name }}-etcd 2379; do
              echo "Waiting for etcd to be ready";
              sleep 5;
            done;
          ']
        {{- end }}
        {{- if .Values.nats.enabled }}
        - name: check-nats
          image: {{ .Values.image.busybox.repository }}:{{ .Values.image.busybox.tag }}
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
          command: ['sh', '-c', '
            until nc -zv {{ .Release.Name }}-nats 4222; do
              echo "Waiting for NATS to be ready...";
              sleep 2;
            done;
          ']
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}-alertquerier
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if .Values.enterprise.enabled }}
          image: "{{ .Values.image.enterprise.repository }}:{{ .Values.image.enterprise.tag | default .Chart.AppVersion }}"
          {{- else }}
          image: "{{ .Values.image.oss.repository }}:{{ .Values.image.oss.tag | default .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.config.ZO_HTTP_PORT }}
            - name: grpc
              containerPort: {{ .Values.config.ZO_GRPC_PORT }}
          {{- if .Values.probes.alertquerier.enabled }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.config.ZO_HTTP_PORT }}
            initialDelaySeconds: {{ .Values.probes.alertquerier.config.livenessProbe.initialDelaySeconds | default 10 }}
            periodSeconds: {{ .Values.probes.alertquerier.config.livenessProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.probes.alertquerier.config.livenessProbe.timeoutSeconds | default 10 }}
            successThreshold: {{ .Values.probes.alertquerier.config.livenessProbe.successThreshold | default 1 }}
            failureThreshold: {{ .Values.probes.alertquerier.config.livenessProbe.failureThreshold | default 3 }}
            terminationGracePeriodSeconds: {{ .Values.probes.alertquerier.config.livenessProbe.terminationGracePeriodSeconds | default 30 }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.config.ZO_HTTP_PORT }}
            initialDelaySeconds: {{ .Values.probes.alertquerier.config.readinessProbe.initialDelaySeconds | default 10 }}
            periodSeconds: {{ .Values.probes.alertquerier.config.readinessProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.probes.alertquerier.config.readinessProbe.timeoutSeconds | default 10 }}
            successThreshold: {{ .Values.probes.alertquerier.config.readinessProbe.successThreshold | default 1 }}
            failureThreshold: {{ .Values.probes.alertquerier.config.readinessProbe.failureThreshold | default 3 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources.alertquerier | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "openobserve.fullname" . }}
            - configMapRef:
                name: {{ include "openobserve.fullname" . }}-alertquerier
            - secretRef:
                name: {{ if .Values.externalSecret.enabled }}{{ .Values.externalSecret.name }}{{ else }}{{ include "openobserve.fullname" . }}{{ end }}
          env:
            - name: ZO_NODE_ROLE
              value: "querier"
            - name: ZO_NODE_ROLE_GROUP
              value: "background"
            {{- with .Values.extraEnv }}
            {{- toYaml . |  nindent 12 }}
            {{- end }}
            {{- with .Values.alertquerier.extraEnv }}
            {{- toYaml . |  nindent 12 }}
            {{- end }}
          {{- if .Values.alertquerier.persistence.enabled }}
          volumeMounts:
            - name: cache
              mountPath: /data
          {{- end }}
      {{- with .Values.nodeSelector.alertquerier }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity.alertquerier }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations.alertquerier }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.alertquerier.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: cache
      spec:
        accessModes:
          {{- range .Values.alertquerier.persistence.accessModes }}
            - {{ . | quote }}
          {{- end }}
        resources:
          requests:
            storage: {{ .Values.alertquerier.persistence.size }}
        storageClassName: {{ .Values.alertquerier.persistence.storageClass }}
  {{- end }}
