{{- if and .Values.enterprise.enabled .Values.enterprise.dex.enabled | default false }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openobserve.fullname" . }}-dex
  namespace: {{ .Release.Namespace | quote }}
{{- end }}

