{{- if and .Values.enterprise.enabled .Values.enterprise.dex.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "openobserve.fullname" . }}-dex
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "openobserve.labels" . | nindent 4 }}
data:
  config.docker.yaml: | {{ .Values.enterprise.dex.config | toYaml | nindent 4 }}
{{- end }}

