apiVersion: v1
kind: Service
metadata:
  name: {{ include "openobserve.fullname" . }}-ingester
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "openobserve.labels" . | nindent 4 }}
    prometheus.io/scrape: "true"
    role: ingester
  {{- with .Values.serviceIngester.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.serviceIngester.type }}
  ports:
    - port: {{ .Values.serviceIngester.http_port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.serviceIngester.grpc_port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "openobserve.selectorLabels" . | nindent 4 }}
    role: ingester
