{{- if and .Values.enterprise.enabled .Values.enterprise.openfga.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openobserve.fullname" . }}-openfga
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: openfga
{{- end }}    
