{{- if and .Values.enterprise.enabled .Values.enterprise.openfga.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openobserve.fullname" . }}-openfga
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openfga
  template:
    metadata:
      labels:
        app: openfga
    spec:
      initContainers:
        - name: openfga-migrate
          image: {{ .Values.enterprise.openfga.image.repository }}:{{ .Values.enterprise.openfga.image.tag }}
          imagePullPolicy: {{ .Values.enterprise.openfga.image.pullPolicy }}
          command: ['/openfga', 'migrate']
          env:
            - name: OPENFGA_DATASTORE_ENGINE
              value: postgres
            {{- if .Values.postgres.enabled }}
            - name: OPENFGA_DATASTORE_URI
              value: "postgres://openobserve:{{ .Values.postgres.spec.password }}@{{ include "openobserve.fullname" . }}-postgres-rw.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:5432/app?sslmode=disable"
            {{- else if .Values.auth.ZO_META_POSTGRES_DSN }}
            - name: OPENFGA_DATASTORE_URI
              value: "{{ .Values.auth.ZO_META_POSTGRES_DSN }}"
            {{- else if .Values.config.ZO_META_POSTGRES_DSN }}
            - name: OPENFGA_DATASTORE_URI
              value: "{{ .Values.config.ZO_META_POSTGRES_DSN }}"
            {{- end }}
          envFrom:
            - secretRef:  # postgres detail can be picked up from secret if not found anywhere else
                name: {{ if .Values.externalSecret.enabled }}{{ .Values.externalSecret.name }}{{ else }}{{ include "openobserve.fullname" . }}{{ end }}
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
      containers:
        - name: openfga
          image: {{ .Values.enterprise.openfga.image.repository }}:{{ .Values.enterprise.openfga.image.tag }}
          imagePullPolicy: IfNotPresent
          command: ['/openfga', 'run']
          env:
            - name: OPENFGA_DATASTORE_ENGINE
              value: postgres
            {{- if .Values.postgres.enabled }}
            - name: OPENFGA_DATASTORE_URI
              value: "postgres://openobserve:{{ .Values.postgres.spec.password }}@{{ include "openobserve.fullname" . }}-postgres-rw.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:5432/app?sslmode=disable"
            {{- else if .Values.auth.ZO_META_POSTGRES_DSN }}
            - name: OPENFGA_DATASTORE_URI
              value: "{{ .Values.auth.ZO_META_POSTGRES_DSN }}"
            {{- else if .Values.config.ZO_META_POSTGRES_DSN }}
            - name: OPENFGA_DATASTORE_URI
              value: "{{ .Values.config.ZO_META_POSTGRES_DSN }}"
            {{- end }}
            - name: OPENFGA_LOG_FORMAT
              value: json
          envFrom:
            - secretRef:
                name: {{ if .Values.externalSecret.enabled }}{{ .Values.externalSecret.name }}{{ else }}{{ include "openobserve.fullname" . }}{{ end }}
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8081
              name: grpc
          {{- if .Values.probes.openfga.enabled }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.config.ZO_HTTP_PORT }}
            initialDelaySeconds: {{ .Values.probes.openfga.config.livenessProbe.initialDelaySeconds | default 10 }}
            periodSeconds: {{ .Values.probes.openfga.config.livenessProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.probes.openfga.config.livenessProbe.timeoutSeconds | default 10 }}
            successThreshold: {{ .Values.probes.openfga.config.livenessProbe.successThreshold | default 1 }}
            failureThreshold: {{ .Values.probes.openfga.config.livenessProbe.failureThreshold | default 3 }}
            terminationGracePeriodSeconds: {{ .Values.probes.openfga.config.livenessProbe.terminationGracePeriodSeconds | default 30 }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.config.ZO_HTTP_PORT }}
            initialDelaySeconds: {{ .Values.probes.openfga.config.readinessProbe.initialDelaySeconds | default 10 }}
            periodSeconds: {{ .Values.probes.openfga.config.readinessProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.probes.openfga.config.readinessProbe.timeoutSeconds | default 10 }}
            successThreshold: {{ .Values.probes.openfga.config.readinessProbe.successThreshold | default 1 }}
            failureThreshold: {{ .Values.probes.openfga.config.readinessProbe.failureThreshold | default 3 }}
          {{- end }}
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
{{- end }}
