{{- if .Values.reportserver.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openobserve.fullname" . }}-reportserver
  labels:
    {{- include "openobserve.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount.reportserver }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "openobserve.selectorLabels" . | nindent 6 }}
      role: reportserver
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        checksum/specific-config: {{ include (print $.Template.BasePath "/reportserver-configmap.yaml") . | sha256sum }}
        checksum/generic-config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "openobserve.selectorLabels" . | nindent 8 }}
        role: reportserver
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openobserve.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-reportserver
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.reportserver.repository }}:{{ .Values.image.reportserver.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.config }}
          envFrom:
            - configMapRef:
                name: {{ include "openobserve.fullname" . }}
            - configMapRef:
                name: {{ include "openobserve.fullname" . }}-reportserver
            - secretRef:
                name: {{ if .Values.externalSecret.enabled }}{{ .Values.externalSecret.name }}{{ else }}{{ include "openobserve.fullname" . }}{{ end }}
          {{- end }}
          env:
            - name: ZO_NODE_ROLE
              value: "reportserver"
            {{- with .Values.extraEnv }}
            {{- toYaml . |  nindent 12 }}
            {{- end }}
            {{- with .Values.reportserver.extraEnv }}
            {{- toYaml . |  nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.config.ZO_HTTP_PORT }}
              protocol: TCP
          {{- if .Values.probes.reportserver.enabled }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.config.ZO_HTTP_PORT }}
            initialDelaySeconds: {{ .Values.probes.reportserver.config.livenessProbe.initialDelaySeconds | default 10 }}
            periodSeconds: {{ .Values.probes.reportserver.config.livenessProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.probes.reportserver.config.livenessProbe.timeoutSeconds | default 10 }}
            successThreshold: {{ .Values.probes.reportserver.config.livenessProbe.successThreshold | default 1 }}
            failureThreshold: {{ .Values.probes.reportserver.config.livenessProbe.failureThreshold | default 3 }}
            terminationGracePeriodSeconds: {{ .Values.probes.reportserver.config.livenessProbe.terminationGracePeriodSeconds | default 30 }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.config.ZO_HTTP_PORT }}
            initialDelaySeconds: {{ .Values.probes.reportserver.config.readinessProbe.initialDelaySeconds | default 10 }}
            periodSeconds: {{ .Values.probes.reportserver.config.readinessProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.probes.reportserver.config.readinessProbe.timeoutSeconds | default 10 }}
            successThreshold: {{ .Values.probes.reportserver.config.readinessProbe.successThreshold | default 1 }}
            failureThreshold: {{ .Values.probes.reportserver.config.readinessProbe.failureThreshold | default 3 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources.reportserver | nindent 12 }}
      {{- with .Values.nodeSelector.reportserver }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity.reportserver }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations.reportserver }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
