{{- if and .Values.reportserver.enabled .Values.autoscaling.enabled  }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "openobserve.fullname" . }}-reportserver
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "openobserve.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "openobserve.fullname" . }}-reportserver
  minReplicas: {{ .Values.autoscaling.reportserver.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.reportserver.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.reportserver.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.reportserver.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.reportserver.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
