{{- if .Values.reportserver.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openobserve.fullname" . }}-reportserver
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "openobserve.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.http_port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "openobserve.selectorLabels" . | nindent 4 }}
    role: reportserver
{{- end }}