apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openobserve.fullname" . }}-router
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "openobserve.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.router.enabled }}
  replicas: {{ .Values.replicaCount.router }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "openobserve.selectorLabels" . | nindent 6 }}
      role: router
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        checksum/specific-config: {{ include (print $.Template.BasePath "/router-configmap.yaml") . | sha256sum }}
        checksum/generic-config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "openobserve.selectorLabels" . | nindent 8 }}
        role: router
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openobserve.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- if .Values.etcd.enabled }}
        - name: check-etcd
          image: {{ .Values.image.busybox.repository }}:{{ .Values.image.busybox.tag }}
          command: ['sh', '-c', '
            until nc -z {{ .Release.Name }}-etcd 2379; do
              echo "Waiting for etcd to be ready";
              sleep 5;
            done;
          ']
        {{- end }} 
        {{- if .Values.nats.enabled }}
        - name: check-nats
          image: {{ .Values.image.busybox.repository }}:{{ .Values.image.busybox.tag }}
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
          command: ['sh', '-c', '
            until nc -zv {{ .Release.Name }}-nats 4222; do
              echo "Waiting for NATS to be ready...";
              sleep 2;
            done;
          ']
         {{- end }} 
      containers:
        - name: {{ .Chart.Name }}-router
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if .Values.enterprise.enabled }}
          image: "{{ .Values.image.enterprise.repository }}:{{ .Values.image.enterprise.tag | default .Chart.AppVersion }}"
          {{- else }}
          image: "{{ .Values.image.oss.repository }}:{{ .Values.image.oss.tag | default .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.config.ZO_HTTP_PORT }}
            - name: grpc
              containerPort: {{ .Values.config.ZO_GRPC_PORT }}
          {{- if .Values.probes.router.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.config.ZO_BASE_URI | default "" }}/healthz
              port: {{ .Values.config.ZO_HTTP_PORT }}
            initialDelaySeconds: {{ .Values.probes.router.config.livenessProbe.initialDelaySeconds | default 10 }}
            periodSeconds: {{ .Values.probes.router.config.livenessProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.probes.router.config.livenessProbe.timeoutSeconds | default 10 }}
            successThreshold: {{ .Values.probes.router.config.livenessProbe.successThreshold | default 1 }}
            failureThreshold: {{ .Values.probes.router.config.livenessProbe.failureThreshold | default 3 }}
            terminationGracePeriodSeconds: {{ .Values.probes.router.config.livenessProbe.terminationGracePeriodSeconds | default 30 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.config.ZO_BASE_URI | default "" }}/healthz
              port: {{ .Values.config.ZO_HTTP_PORT }}
            initialDelaySeconds: {{ .Values.probes.router.config.readinessProbe.initialDelaySeconds | default 10 }}
            periodSeconds: {{ .Values.probes.router.config.readinessProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.probes.router.config.readinessProbe.timeoutSeconds | default 10 }}
            successThreshold: {{ .Values.probes.router.config.readinessProbe.successThreshold | default 1 }}
            failureThreshold: {{ .Values.probes.router.config.readinessProbe.failureThreshold | default 3 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources.router | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "openobserve.fullname" . }}
            - configMapRef:
                name: {{ include "openobserve.fullname" . }}-router
            - secretRef:
                name: {{ if .Values.externalSecret.enabled }}{{ .Values.externalSecret.name }}{{ else }}{{ include "openobserve.fullname" . }}{{ end }}
          env:
            - name: ZO_NODE_ROLE
              value: "router"
            {{- with .Values.extraEnv }}
            {{- toYaml . |  nindent 12 }}
            {{- end }}
            {{- with .Values.router.extraEnv }}
            {{- toYaml . |  nindent 12 }}
            {{- end }}
            
      {{- with .Values.nodeSelector.router }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity.router }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations.router }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
