apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openobserve.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "openobserve.labels" . | nindent 4 }}
type: Opaque
stringData:
  ZO_ROOT_USER_EMAIL: "{{ .Values.auth.ZO_ROOT_USER_EMAIL }}"
  ZO_ROOT_USER_PASSWORD: "{{ .Values.auth.ZO_ROOT_USER_PASSWORD }}"
  {{- if not .Values.minio.enabled }}
  ZO_S3_ACCESS_KEY: "{{ .Values.auth.ZO_S3_ACCESS_KEY }}"
  {{- else }}
  ZO_S3_ACCESS_KEY: "{{ .Values.minio.rootUser }}"
  {{- end }}
  {{- if not .Values.minio.enabled }}
  ZO_S3_SECRET_KEY: "{{ .Values.auth.ZO_S3_SECRET_KEY }}"
  {{- else }}
  ZO_S3_SECRET_KEY: "{{ .Values.minio.rootPassword }}"
  {{- end }}
